# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Late Nite Code
tagline:          ''
description:      'For the Algo Owl { 🦉 }'
url:              http://latenitecoding.github.io
baseurl:          /

author:
  name:           'Ian Riley'
  url:            https://twitter.com/latenitecode

paginate:         5

# Custom vars
version:          2022.10.27

github:
  repo:           https://github.com/latenitecoding.github.io
